### ISSUE TITLE
'X' button on form element not functional

### ISSUE THREAD

**Issue by LiamHurley** [Milchreis/UiBooster#60] opened 2021-12-29 00:26 UTC
The 'X' button on the form functions the same as the OK button, code will continue to run after attempting to close the form. Not sure if this is by design or not but other than that the form element is great.

**Comment by Milchreis** [comment] 2021-12-29 18:53
Hi Liam,

thank you for your issue. You are right the form will be closed by "OK" and "X" by design, but the code should not further. Do you have a code example for me to understand it completly?

**Comment by LiamHurley** [comment] 2022-01-11 19:21
> 

Hi, sorry for taking so long to get back to you, I've only just seen this.

`String s = "Placeholder 1";
		String d = "Placeholder 2";
		UiBooster booster = new UiBooster();
		Form form = booster.createForm("Personal information")
				.addText("Whats your first name?", s)
				.addText("Airport Name", d)
				.show();

		System.out.println("should not get here");`

For example if you run that code and click the 'X' button to try and exit, "should not get here will still print". 

Hope that was useful :)

**Comment by Milchreis** [comment] 2022-01-14 06:54
Hi Liam,

ok, now I understand 😊 The show()-method blocks the code flow until you close the form, no matter which close button you choose (x or ok). After the close operation the code flow continues. There is no way to stop the complete program by clicking the X button.

Currently you have to check the close action and stop the program as following:
````java
String s = "Placeholder 1";
String d = "Placeholder 2";
UiBooster booster = new UiBooster();
Form form = booster.createForm("Personal information")
		.addText("Whats your first name?", s)
		.addText("Airport Name", d)
		.show();

if(form.isClosedByUser())
    System.exit(-1);

System.out.println("should not get here");
```
For the next version I will implement an close Listener. In that way an action could be defined in the createForm-chain instead after the definition.

**Comment by LiamHurley** [comment] 2022-01-15 19:53
Hi Milchreis,

I just ran the code snippet you posted and unfortunately that doesn't seem to work for me either.  "should not get here" still prints even with the manual check.

**Comment by Milchreis** [comment] 2022-01-16 10:32
Hi Liam,

it's not possible for me to reproduce this issue. I used the version 1.14.0 and with the code snippet I didn't get "should not get here" if I press the X-button. Which version do you use?

**Comment by Milchreis** [comment] 2022-01-16 18:21
Hey Liam,

I implemented a new feature and saw some flaws in the internasl for the `form.isClosedByUser()` method. Maybe it fixed your issue. Please check the new version 1.14.1 and let me know if it works for you.

**Comment by LiamHurley** [comment] 2022-01-16 19:51
Awesome, I'll give it a try tomorrow and let you know how it goes. Thank you :)

**Comment by vectorcs1993** [comment] 2022-01-27 04:20
Hello, unfortunately the isClosedByUser() function always returns false, both when closing the form with the "X" button and when pressing the "OK" button:( version 1.14.1

**Comment by Milchreis** [comment] 2022-01-27 06:55
hi @vectorcs1993 

thank you very much for your reply. I am not sure why it's not possible to me to reproduce the issue, but on the weekend I will try to fix it.

**Comment by vectorcs1993** [comment] 2022-01-27 07:21
Thank you, is it possible to add an event listener to handle clicking the "OK" button? then there will be no need to solve this problem :)

**Comment by Milchreis** [comment] 2022-01-27 14:12
Yes, with version 1.14.1 I added a close listener. You can use it as following:

```java
new UiBooster()
  .createForm("Personal information")
  .addText("Whats your first name?")
  .setCloseListener((f) -> {
      System.out.println("Is form closed by user? " + f.isClosedByUser());
  })
  .show();
```

I hope it works for you. A complete example can you find [here](https://github.com/Milchreis/UiBooster/blob/master/src/test/java/de/milchreis/uibooster/FormBuilderTest.java#L120)

**Closed** 2022-04-06 14:27 UTC
